# Site settings
title: Sytac.io
email: info@sytac.io
meetupurl: http://www.meetup.com/Sytac-Dev-Jam
description: > # this means to ignore newlines until "baseurl:"
  By developers, for developers. Brought to you with <3 by the fine people at Sytac.
baseurl: ""
url: "http://sytac.io"
github_username: sytac
# Build settings
markdown: kramdown
